### ISSUE TITLE
Jquery >2 support

### ISSUE THREAD

**Issue by mteichtahl** [collective/jquery.recurrenceinput.js#27]
Are there any plans to support jquery >2.0 ?

**Comment by thet** [comment]
We are already using it on jQuery 1.11, so it should also work on jQuery 2. The trick was to include jquerytools from this branch/fork: https://github.com/collective/jquerytools/tree/dev

Still, we might need to rewrite parts of recurrenceinput for loosing dependencies on external libraries or at least to reuse libraries we already use in https://github.com/plone/mockup/

I keep this issue open to remind myself about re-validating the jQuery 2.0 issue.

**Comment by thet** [comment]
Closed via: https://github.com/collective/jquery.recurrenceinput.js/commit/d701ee5ca9ccbfe75d9ef31e71bf7245f8625491

**Comment by mteichtahl** [comment]
Johannes

The bower dependency is still <1.9 so I can bring it in via bower

**Comment by thet** [comment]
fixed and released. please use the 1.5 version.

**Comment by mteichtahl** [comment]
Works very well 

Thank you 

I'm working through the css to give it a bootstrap 3 feel. This will be in the form of a less file with specific overrides. Would you like me to PR this so other can use it ?

**Comment by thet** [comment]
i'm looking forward for the pull request!
in general, we should to avoid dependencies on external libraries or frameworks, including bootstrap. but a nicer look is much appreciated.

**Comment by mteichtahl** [comment]
I'll have something to you over the coming days

**Comment by mteichtahl** [comment]
johannes

What is the best way to read out the RRULE string ?


-----------------------------------------------
Marc Teichtahl
marc@teichtahl.com
Ph: +61 434 100 259
http://www.teichtahl.com
